services:
  - type: web
    name: portail-c2b-entreprise
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATA_DIR
        value: /opt/render/project/data
      - key: PYTHONUNBUFFERED
        value: 1
      - key: ADMIN_PASSWORD
        generateValue: true
    disk:
      name: c2b-data
      mountPath: /opt/render/project/data
      sizeGB: 1